<?php
include_once '../../connection.php';
$con = connect();

$outputheader='';

date_default_timezone_set('Asia/Manila');
            $timestamp = time();
            $time = date("h:i:s A", $timestamp);

            $mydate=getdate(date("U"));
            $daterec = "$mydate[weekday], $mydate[month] $mydate[mday], $mydate[year]";


$outputheader.='<table class="table-bordered">
                    <tr> 
                        <th colspan="12">ARELLANO UNIVERSITY ANDRES BONIFACIO CAMPUS</th>
                    </tr>
                    <tr> 
                        <th colspan="12">ANDRES BONIFACIO CAMPUS</th>
                    </tr>
                    <tr> 
                        <th colspan="12">ALL STUDENT TIME RECORDS</th>
                    </tr>
                    <tr> 
                        <th colspan="12"></th>
                    </tr>
                    <tr>
                        <td> </td>
                        <td>DATE GENERATED:</td>
                        <td colspan="3">'.$daterec.'</td>
                    </tr>
                    <tr>
                        <td> </td>
                        <td>TIME GENERATED:</td>
                        <td colspan="3">'.$time.'</td>
                    </tr>
                    <tr>
                        <td> </td>
                        <td>GENERATED BY:</td>
                        <td colspan="3">TIME NOTIFY ADMIN</td>
                    </tr>
                </table>';

$output='';

$output .='
        <table class="table" bordered="1">
            <thead>
                <tr class="heading">
                <th scope="col">ID</th>
                <th scope="col">STUDENT NUMBER</th>
                <th scope="col">STUDENT NAME</th>
                <th scope="col">DEPARTMENT</th>
                <th scope="col">GRADE</th>
                <th scope="col">DATE</th>
                <th scope="col">TIME</th>
                <th scope="col">TYPE</th>
                </tr>
            </thead>
                <tbody>';
                            $sql="SELECT *
                            FROM students
                            INNER JOIN time_in_records ON students.stud_id = time_in_records.stud_id ORDER BY age";
                              
                            $result=mysqli_query($con,$sql);

                            if($result){
                                while($row=mysqli_fetch_assoc($result))
                                {
                                    
                                    $stud_id=$row['stud_id']; 
                                    $studnum=$row['studnum']; 
                                    $lastname=$row['lastname'];
                                    $middlename=$row['middlename'];
                                    $firstname=$row['firstname'];
                                    $department=$row['department'];
                                    $grade_year=$row['grade_year'];

                                    $daterec=$row['daterec'];
                                    $time=$row['time'];
                                    $type=$row['type'];


                                    $_SESSION['student_id'] = $stud_id; //Session StudID

                                    
                                    $output .='<tr>
                                            <td ><center>'.$stud_id.'</center></td>
                                            <td ><center>'.$studnum.'</center></td>
                                            <td ><center>'.$lastname.', '.$firstname.' '.$middlename.'</center></td>  
                                            <td ><center>'.$department.'</center></td> 
                                            <td ><center>'.$grade_year.'</center></td>   
                                            <td ><center>'.$daterec.'</center></td>   
                                            <td ><center>'.$time.'</center></td>
                                            <td ><center>'.$type.'</center></td> 
                                        </tr>
                                    ';
                                }
                            }
                        $output.='</table>';                                
                            
                       


header("Content-Type: application/xls");
header("Content-Disposition: attachment; Filename =all_student_time_record.xls ");

echo '<br>';
echo $outputheader;
echo '<br>';
echo $output;


?>